### ISSUE TITLE
Getting `Input type (c10::Half) and bias type (float) should be the same` error when calling `Replicate.run`

### ISSUE THREAD

**Issue by raulmabe-labhouse** [replicate/replicate-javascript#221]
It was working all well, but suddenly this error is getting thrown at every request I send:
```
Prediction failed: Input type (c10::Half) and bias type (float) should be the same
    at Replicate.wait (/workspace/node_modules/replicate/index.js:379:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Replicate.run (/workspace/node_modules/replicate/index.js:154:18)
```

Version `"replicate": "^0.28.1"`

Let me know if I can provide with more info.

**Comment by mattt** [comment]
Hi @raulmabe-labhouse. This looks like an error produced by the model. If you go to replicate.com, you should see a failed prediction on your dashboard. If you share the prediction ID, I can take a look.

**Comment by raulmabe-labhouse** [comment]
The prediction ID is `ohjm643bfvhphu4shrpjruz45u`.

It must have to do with a NSFW prompt I tested (`hitler ultra hyperreslistic close up`) before this request... All requests after the NSFW one were producing this exact error, but all requests made before were working perfectly...
