### ISSUE TITLE
"Error: API request failed: Unprocessable Entity" when running with lora-training

### ISSUE THREAD

**Issue by harriswong** [replicate/replicate-javascript#43]
Hi! I am trying to train a model by providing my own .zip input using the API. I'm following the instructions here (https://replicate.com/cloneofsimo/lora-training/api) but getting an error:
```
import Replicate from "replicate";

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

const output = await replicate.run(
  "cloneofsimo/lora-training:b2a308762e36ac48d16bfadc03a65493fe6e799f429f7941639a6acec5b276cc",
  {
    input: {
      instance_data: "..."
    }
  }
);
```

It results with 
```
> node index.js

/node_modules/replicate/index.js:143
      throw new Error(`API request failed: ${response.statusText}`);
            ^

Error: API request failed: Unprocessable Entity
    at Replicate.request (/node_modules/replicate/index.js:143:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Replicate.createPrediction (/node_modules/replicate/lib/predictions.js:24:22)
    at async Replicate.run (/node_modules/replicate/index.js:93:24)
    at async trainModel (file:///index.js:25:20)

Node.js v18.15.0
```

### What I tested
I thought maybe using predictions for `lora-training` is not the right function. So, I created a new function by changing the `this.predictions` to `this.trainings`
```js
  async runTraining(identifier, options) {
    const pattern =
      /^(?<owner>[a-zA-Z0-9-_]+?)\/(?<name>[a-zA-Z0-9-_]+?):(?<version>[0-9a-fA-F]+)$/;
    const match = identifier.match(pattern);

    if (!match) {
      throw new Error(
        'Invalid version. It must be in the format "owner/name:version"'
      );
    }

    const { owner, name, version } = match.groups;
    const training = await this.trainings.create(
      owner,
      name,
      version,
      options,
    );

    if (training.status === 'failed') {
      throw new Error(`Training failed: ${training.error}`);
    }

    return training.output;
  }
```
Now I am getting `Error: API request failed: Bad Request` and I guess I am missing `options.destination` [here](https://github.com/replicate/replicate-javascript/blob/586cd6187cd79f00ab00752c5dbfa697c6a222e6/lib/trainings.js#L8).

Should `{username}/{model_name}` be my username or the person owning the model? And does this mean we are uploading our .zip to their account? Thanks!

**Comment by harriswong** [comment]
Hi @mattt, thanks for the reply! I just ran the code again and now I get a different error `Error: Prediction failed: File is not a zip file`. I am using the Google Drive's share file. The link of the file is in the format of `https://drive.google.com/file/d/xyzxyzxyzxyzxyz/view?usp=sharing`

The code I am testing with is this:
```js
import Replicate from "replicate";

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

const trainModel = async () => {
  // Train the model
  const lora_url = await replicate.run(
    "cloneofsimo/lora-training:b2a308762e36ac48d16bfadc03a65493fe6e799f429f7941639a6acec5b276cc",
    {
      input: {
        instance_data: "https://drive.google.com/file/d/1Lke8o_xyzxyzxyzxyzxyzxyzxyz/view?usp=sharing",
        task: "face"
      }
    }
  )
  console.log(lora_url);
  return lora_url;
}

trainModel();

```

I can now see a failed run inside https://replicate.com/predictions with the following
```
File "/root/.pyenv/versions/3.10.9/lib/python3.10/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "/src/predict_basic.py", line 114, in predict
extract_zip_and_flatten(instance_data, cog_instance_data)
File "/src/common.py", line 27, in extract_zip_and_flatten
with ZipFile(str(zip_path), "r") as zip_ref:
File "/root/.pyenv/versions/3.10.9/lib/python3.10/zipfile.py", line 1267, in __init__
self._RealGetContents()
File "/root/.pyenv/versions/3.10.9/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
I will try with a .zip file instead of the Google Drive's. Thanks!
