### ISSUE TITLE
`replicate.run` "sometimes" returns `Not found` 

### ISSUE THREAD

**Issue by hnykda** [replicate/replicate-javascript#68]
Hi.

I am not sure why and cannot find out a reason, but the following code:

```
import Replicate from 'replicate';

const MODEL = 'cjwbw/clip-vit-large-patch14';
const VERSION = '566ab1f111e526640c5154e712d4d54961414278f89d36590f1425badc763ecb';

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

export async function predict(input_image: string, target: string): Promise<number> {
  console.log(`Prediction for ${target} ...${input_image.slice(-50)} with ${MODEL}:${VERSION}`);
  const input = { text: `${target} | `, image: input_image };
  const output = await replicate.run(`${MODEL}:${VERSION}`, { input });
  console.log(`Prediction for ...${input_image.slice(-50)}: ${output[0]}`);
  return output[0];
}
```

and then we do something like:

```
const promises = [predict(...), predict(...)]
...
const results = await Promise.all(promises)
```

worked just fine for about 10k of requests. But this night, we started to sometimes get 

```
2023-05-10T09:00:49.435Z  2023-05-10T09:00:49.364Z      8b9a495a-5846-4938-abe2-8f40c9d54985    ERROR   Error while predicting images:  Error: API request failed: Not Found
2023-05-10T09:00:49.435Z      at Replicate.request (/var/task/.next/server/chunks/205.js:133:19)
2023-05-10T09:00:49.435Z      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-10T09:00:49.435Z      at async Replicate.wait (/var/task/.next/server/chunks/205.js:180:33)
2023-05-10T09:00:49.435Z      at async Replicate.run (/var/task/.next/server/chunks/205.js:95:28)
2023-05-10T09:00:49.435Z      at async predict (/var/task/.next/server/chunks/512.js:29:20)
2023-05-10T09:00:49.435Z      at async Promise.all (index 1)
2023-05-10T09:00:49.435Z      at async POST (/var/task/.next/server/app/assignments/imagery/api/route.js:618:23)
```

which is pretty bad... The supper annoying thing is that it works intermittently now - some requests go through, some don't. Also, it seems that the predictions are actually done.

**Comment by hnykda** [comment]
Here is when it happens immediately after working fine for 4 images:

```
Predicting image:  2023-05-10T09:36:14.540Z_0.png
Prediction for building ...L2/5xK/nH94/rH9Y/r773+N6Vg60QQlYzEAAAAAElFTkSuQmCC with cjwbw/clip-vit-large-patch14:566ab1f111e526640c5154e712d4d54961414278f89d36590f1425badc763ecb
Prediction for ...L2/5xK/nH94/rH9Y/r773+N6Vg60QQlYzEAAAAAElFTkSuQmCC: 0.11996390670537949
Predicted image:  2023-05-10T09:36:14.540Z_0.png
Predicting image:  2023-05-10T09:36:14.540Z_1.png
Prediction for building ...aklfbOG62N1d77oiiH0+n/D2cHqR+/fFmGAAAAAElFTkSuQmCC with cjwbw/clip-vit-large-patch14:566ab1f111e526640c5154e712d4d54961414278f89d36590f1425badc763ecb
Prediction for ...aklfbOG62N1d77oiiH0+n/D2cHqR+/fFmGAAAAAElFTkSuQmCC: 0.010242702439427376
Predicted image:  2023-05-10T09:36:14.540Z_1.png
Predicting image:  2023-05-10T09:36:14.540Z_2.png
Prediction for building ...kRxuacxNZ22AuJoxvj/w/2iO7Lai1lWAAAAABJRU5ErkJggg== with cjwbw/clip-vit-large-patch14:566ab1f111e526640c5154e712d4d54961414278f89d36590f1425badc763ecb
Prediction for ...kRxuacxNZ22AuJoxvj/w/2iO7Lai1lWAAAAABJRU5ErkJggg==: 0.0943252444267273
Predicted image:  2023-05-10T09:36:14.540Z_2.png
Predicting image:  2023-05-10T09:36:14.540Z_3.png
Prediction for building ...IukXRzRUSI++0qqSVa0f8BHiMgK9L99dwAAAAASUVORK5CYII= with cjwbw/clip-vit-large-patch14:566ab1f111e526640c5154e712d4d54961414278f89d36590f1425badc763ecb
Error while predicting images data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYAAAAGACAIAAAArpSLoAAACYGVYSWZNTQAqAAAACAAGAQAABAAAAAEAAAGAAQEABAAAAAEAAAGAAQ4AAgAAAAwAAABWARAAAgAAABQAAABiATEAAgAAAA0AAAB2khMAAQAAAdsAAACEAAAAAHNhZGYgYXNkZiBhAHN0YWJpbGl0eS1kaWZmdXNpb24Ac3RhYmlsaXR5LmFpAAAzayldYnZwQjQ6ZU81TmN3ezVmZXovZGM6ZiEkdDdnYStpW2NuRXdpZkwxVzVoNy1sR2diezx4aTVKeHd2USU0ZGVPZURIaXdTUEd2USY+NGYvPzNhMHUjZC0xUltARnhHKXp3M2lRfXRGRERrWT, 4: Error: API request failed: Not Found
```

**Comment by hnykda** [comment]
It happens when fetching the result of the prediction. Maybe it's "too fast"?

![image](https://github.com/replicate/replicate-javascript/assets/2741256/5b8d19f6-de83-40ca-8ffb-0d3f9b95b63e)

**Comment by mattt** [comment]
Hi @hnykda. I'm sorry for any inconvenience this behavior caused you. Thank you for taking the time to write all of this up and share a workaround.

The behavior you saw was a result of some changes we made to our infrastructure over the last 24 hours that temporarily changed write consistency between our API service and our monolith. This caused `GET` requests to newly-created predictions to intermittently return 404. 

As of 13:10 UTC today (~20 minutes ago at time of writing), the API deployed a change that restores write consistency back to what we had before, so you shouldn't be seeing any more 404s like that again.

**Comment by hnykda** [comment]
![](https://media.giphy.com/media/l378giAZgxPw3eO52/giphy.gif)

**Comment by Frontenda** [comment]
same issue on NodeJS React Render.com :  Error: Prediction failed: 404  model = "jagilley/controlnet-hough:854e8727697a057c525cdb45ab037f64ecca770a1769cc52287c2e56472a247b";

**Comment by kirtirajsinh** [comment]
> for any inconvenienc
 
is it resolved? I'm getting the same error when using replicate.run () 

import { replicate } from "@/utils/replicate";
```

export default async function handler(req, res) {
  try {
    let prediction = await replicate.predictions.create({
      version:
        "c0259010b93e7a4102a4ba946d70e06d7d0c7dc007201af443cfc8f943ab1d3c",
      input: {
        prompt:
          "RAW photo, a portrait photo of a latina woman in casual clothes, natural skin, 8k uhd, high quality, film grain, Fujifilm XT3",
      },
    });
    prediction = await replicate.predictions.get(prediction.id);
    console.log(prediction, "prediction result");
    // res.status(200).json(prediction);
  } catch (error) {
    console.log(error);
    res.status(500).json({ error: "An error occurred" });
  }
}
```

**Comment by marvinai** [comment]
still having the same issue on February 2, 2024

**Comment by renet** [comment]
@mattt Thanks for explaining this. As we're currently running into this issue very often, it seems like maybe this has happened again. Can you please verify, or should I open a new ticket for that?

**Comment by mattt** [comment]
@renet I no longer work at Replicate, and unfortunately don't have any insight into what might be happening. I'd recommend opening a new issue or reaching out to support.
